Support alpha channel in `as-hex`
noprompt/garden pull request #203
Opened 2023-04-11 04:48 UTC by ZehCnaS34

Related issue #182

2023-04-11 15:15 UTC, WorldsEndless commented
I'll wait on the merge until one of the more experienced Gardeners chime in @noprompt  @priyatam

2023-04-11 15:20 UTC, WorldsEndless commented on test/garden/color_test.cljc
> +(def hsla-black (color/hsla 0 0 0 0.5))
it would be good to add a test case where the alpha component is 1, as per https://github.com/noprompt/garden/pull/203#discussion_r1162975482

2023-04-11 15:21 UTC, WorldsEndless requested changes
need to test the alpha=1 cases per https://github.com/noprompt/garden/pull/203#discussion_r1162975482

2023-04-11 17:46 UTC, WorldsEndless approved these changes
looks great! I'll give it a day before I do a merge on this, to wait for input.

2023-04-12 17:15 UTC, noprompt commented
@WorldsEndless @harold I don't have the time to review these PRs, however, I trust both of you to make good decisions. 😄

2023-04-12 19:44 UTC, merged